### ISSUE TITLE
Changed translation does not cause content hash to update

### ISSUE THREAD

**Issue by madelson** [privatenumber/webpack-localize-assets-plugin#19]
## Bug description

I am using this plugin to generate webpack bundles like `app.de-DE.d08a7ee51f14f697cec9.js`. 

The hash portion of the file name is generated by webpack:
```
// Content hash comes for free, see https://webpack.js.org/guides/caching/#output-filenames
filename: '[name].[locale].[contenthash].js'
```

I've noticed that the hash is the same for all locales; this is fine and actually kind of desirable because it makes it easier to generate the right path in my template without inspecting the filesystem.

HOWEVER, I've also noticed that changing a translated value does not result in the content hash changing. This is very undesirable for us because it means that updated translations won't bust the cache for users unless some other code on the page independently changes.

## Reproduction steps

Start with the basic plugin setup detailed in the README.

Set the output to include a content hash
```
filename: '[name].[locale].[contenthash].js'
```

webpack -> look at generated files and hashes

Change some locale values in the locales dictionary.

webpack -> generates same hash!

## Environment

- webpack-localize-assets-plugin version: 1.2.4
- Webpack version: 5.52.0
- Operating System: Windows 10
- Node version: 14.17.3
- Package manager (npm/yarn/pnpm) and version: npm 7.20.0

## Workaround

The workaround I've thought of for now is adding a hash of the full locales file to one of my code files and maintaining this via a build step. That way any changes in the translations should result in a new content hash.

**Comment by madelson** [comment]
@privatenumber I'm a bit confused about what you're saying the path forward is:

> [contenthash] should be identical across different locales.

> [contenthash] should reflect the content of the asset, it should be different for each locale.

Also, can you explain what this means?

> Updating the locale should update [contenthash]

What is "updating the locale"? Changing key translations?

@benjamin-hodgson RE `Could you configure the HtmlWebpackPlugin to spit out a lookup table for the hashes into your razor code?`

This idea is definitely appealing. I'm fairly new to webpack so the one thing I'm not sure how to do is how to get at the locale->content hash mapping during the `HtmlWebpackPlugin.getHooks(compilation).beforeAssetTagGeneration` event. I'll have to look into this further.

It does seem like this would be somewhat for someone who is using `HtmlWebPackPlugin` with raw HTML though. Obviously we can get around it via cshtml templating.

**Comment by privatenumber** [comment]
Sorry for the confusion. I had a typo but I fixed it and also added an explanation for the 2nd point.

I also just released https://github.com/privatenumber/webpack-localize-assets-plugin/releases/tag/v1.3.0 with the latest changes.

I hope to address the remaining Webpack 4 contenthash bug soon.

**Comment by privatenumber** [comment]
Closing as there hasn't been much progress on this.

In Webpack 5, we're able to update the content hash because the asset `info` object contains `contenthash` for us to use in a find-and-replace to update.

In Webpack 4, there is no `contenthash` property, making it more challenging to identify what to update. Given Webpack's solution to this in Webpack 5 was to introduce `optiomizations.realContentHash`, I think it's reasonable to say it's not possible.

Still open to ideas if anyone has any.
