### ISSUE TITLE
Provide option to ignore "output.filename must include [locale]"

### ISSUE THREAD

**Issue by nevnein** [privatenumber/webpack-localize-assets-plugin#46]
## Is your feature request related to a problem? Please describe.

Right now, it is required to include [locale] in the output.filename, otherwise an error will be thrown. 
When building a single locale, it might be desirable to have an output that doesn't contain [locale], especially since it's kinda hard to make it play nice with HtmlWebpackPlugin, see https://github.com/privatenumber/webpack-localize-assets-plugin/issues/17

## Describe the solution you'd like

Probably an option, something like `throwOnMissingLocaleInFilename`: if `true` (default) it behaves exactly like it already does, but when manually disabled it just skips the assertion.

## Describe alternatives you've considered

Right now if an output.filename without [locale] is needed there doesn't seem to be any clean way to do it, except manually removing it post-build which doesn't look like a very robust solution.

**Comment by privatenumber** [comment]
Makes sense to remove the `[locale]` requirement in single locale mode.

PR welcome!
